FROM python:3

# dicom comm
EXPOSE 5000

# for scanner is where we insert files
RUN mkdir /mnt/import
COPY examples/ /mnt/import
RUN mkdir /mnt/data

RUN apt update
RUN apt install glusterfs-client -y

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY docker-entrypoint-flask.sh ./
RUN chmod +x docker-entrypoint-flask.sh

COPY py/ ./

ENTRYPOINT [ "/usr/src/app/docker-entrypoint-flask.sh", "./app/Server.py" ]
