FROM python:3

# dicom comm
EXPOSE 11112

# for scanner is where we insert files
RUN mkdir /mnt/import
COPY examples/ /mnt/import
RUN mkdir /mnt/data

RUN apt update
RUN apt install glusterfs-client -y

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY docker-entrypoint.sh ./
RUN chmod +x docker-entrypoint.sh

COPY py/ ./

# CMD [ "python", "./app/Scanner.py", "-c", "file" ]
ENTRYPOINT [ "/usr/src/app/docker-entrypoint.sh", "./app/Scanner.py", "dicom" ]
