# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<-SCRIPT
mkdir /data
echo '192.168.50.20 gluster-client' >> /etc/hosts
echo '192.168.50.21 gluster-server-1' >> /etc/hosts
echo '192.168.50.22 gluster-server-2' >> /etc/hosts
echo '192.168.50.23 gluster-server-3' >> /etc/hosts
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.boot_timeout = 900
  glusterfs_version = "7"
  # We setup three nodes to be gluster hosts, and one gluster client to mount the volume
  (1..3).each do |i|
    config.vm.define vm_name = "gluster-server-#{i}" do |config|
      config.vm.hostname = vm_name
      ip = "192.168.50.#{i+20}"
      config.vm.network :private_network, ip: ip
      config.vm.provision :shell, :inline => $script

      config.vm.provision :shell, :inline => "DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -yq software-properties-common", :privileged => true
      config.vm.provision :shell, :inline => "DEBIAN_FRONTEND=noninteractive add-apt-repository ppa:gluster/glusterfs-#{glusterfs_version}", :privileged => true
      config.vm.provision :shell, :inline => "DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -yq glusterfs-server", :privileged => true
    end
  end
  config.vm.define vm_name = "gluster-client" do |config|
    config.vm.hostname = vm_name
    ip = "192.168.50.20"
    config.vm.network :private_network, ip: ip
    config.vm.provision :shell, :inline => $script

    config.vm.provision :shell, :inline => "DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -yq software-properties-common", :privileged => true
    config.vm.provision :shell, :inline => "DEBIAN_FRONTEND=noninteractive add-apt-repository ppa:gluster/glusterfs-#{glusterfs_version}", :privileged => true
    config.vm.provision :shell, :inline => "DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -yq glusterfs-client", :privileged => true
  end
end
