plugin:
    param: 1

app:
    # this 
    destination_path: z:\
    # this is dispatcher queue
    # it may be plugin queue directly if needed (dispatcher is a plugin)
    queue: 
        name: qc_make
        type: RMQ
        host: 192.168.50.11
        user: admin
        password: sa
    database:
        type: DBMongo
        host: 192.168.50.11
        port: 27017
        db: ai
        collection: history.jobs
