plugin:
    mail:
        smtp_host: smtp.gmail.com
        smtp_port: 587
        smtp_user: marcin.dudkowski@cubegames.pl
        smtp_password: eknwuwrivelalvux
        email_subject: Error during recieving DICOM data
        email_from: Test Account <marcin.dudkowski@cubegames.pl>
        email_to:
            - marcin.dudkowski@fortrus.com
            # - marcin.dudkowski@fortrus.com
            # - dudi@cubegames.pl
        # https://security.google.com/settings/security/apppasswords
        error_message_template: |
            <p>There is a problem:</p>
            <p><span style="font-size: 150%"><b>{}</b></span></p>
            <p>Please check is everything ok with system configuration.</p>

app:
    # this 
    destination_path: z:\
    # this is dispatcher queue
    # it may be plugin queue directly if needed (dispatcher is a plugin)
    queue: 
        name: validate
        type: RMQ
        host: 192.168.50.11
        user: admin
        password: sa
    database:
        type: DBMongo
        host: 192.168.50.11
        port: 27017
        db: ai
        collection: history.jobs
