## file scanninig plugin

# configuration specific to plugin settings
# every plugin may have different one
plugin:
    path: /mnt/import
    study: true
    attachemnts:
        - .dcm
    
    # file processing is based on rdy files
    # when this file is prosent main file will be processed
    ready_file: .rdy
    scanning_period: 5

# this is scanner (app / could be something else) config itself
app:
    destination_path: /mnt/data
    # this is dispatcher queue
    # it may be plugin queue directly if needed (dispatcher is a plugin)
    queue: 
        name: dispatcher
        type: RMQ
        host: rmq
        user: admin
        password: sa
    database:
        type: DBMongo
        host: db
        port: 27017
        db: ai
        collection: history.jobs
